### PR TITLE
GH-241: Added guard to metrics processor before saving the file.

### PR DESCRIPTION
**Pull request by kittaakos**
Task: #241.
Closes: #241

I am not sure whether this is the correct solution or not. @crapo, please review my changes. Thank you! 

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by crapo** [comment]
@kittaakos , I'm a little puzzled on this one. It seems to me that the first time you run metrics processing on a project, the file wouldn't exist, and this would prevent metrics from ever being written to a file. Wouldn't we test the parent folder (OwlModels) in the project and if it exists instead?

**Comment by kittaakos** [comment]
@crapo, thanks for looking into that. That was my impression too. So the file does not exist at the first place, makes sense. Testing the `OwlModels` folder would be much better but if I remember correctly, the `OwlModels` folder exists for those tests.

This is what I would recommend then: close this PR without merging it, we can live with this minor cosmetic problem and we will switch from `file://` URI scheme to `synthetic` later when we bump up the Xtext version. What do you thing?

**Comment by crapo** [comment]
I thought that since it's a test, the OwlModels folder wouldn't exist as a File. Don't all tests have synthetic URIs? We have a method isSyntheticUri(String modelFilderPahtname, Resource resource). We can call methods in the model processor from the metrics processor, so can we just use this method to decide whether to save metrics?

**Comment by kittaakos** [comment]
> Don't all tests have synthetic URIs?

No, tests that were created for the SADL-web prototype work on real files from the disk.

**Comment by crapo** [comment]
Close this PR without merging it as we can live with this minor cosmetic problem and we will switch from file:// URI scheme to synthetic later when we bump up the Xtext version.

**Pull request closed without merging**
