### PR TITLE
GH-336: Fixed the external download functionality for HTTP URIs.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes: #336.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by kittaakos** [comment]
I have used the following external model definition:
```
--This is a list of URLs of OWL model files to add to the external models directory for this project.
--TO DO:  Add your list of URLs

http://sadl.sourceforge.net/owl/aulo.owl
http://sadl.sourceforge.net/owl/apvf.owl
file:///Users/akos.kitta/Desktop/time-entry.owl
```

The `time-entry.owl` file was at `/Users/akos.kitta/Desktop/time-entry.owl` in my case.

**Comment by crapo** [comment]
This does not work for file URLs on Windows. Not sure how it works on Unix-style paths, but on windows, the from ExternalEmfModelDownloader, line 97, to SadlUtils.externalUrlToRelativePath has as input argument "file:/c:/tmp/time-entry.owl". These two lines in the called method give this result:
urlPath="/c:/tmp/time-entry.owl" and since neither the if nor the else matches this is what is returned and line 164 in downloadURL gives:
outputPath="D:\Users\200005201\aske-workspace\TA1\ModelsFromCode\Ontologies\externalmodels\/c:/tmp/time-entry.owl"
which leads on line 167 to the error:
java.io.FileNotFoundException: D:\Users\200005201\aske-workspace\TA1\ModelsFromCode\Ontologies\externalmodels\c:\tmp\time-entry.owl (The filename, directory name, or volume label syntax is incorrect).

**Comment by kittaakos** [comment]
Thanks for checking, I have to do this on my Windows image then.

**Comment by kittaakos** [comment]
Now I see what is causing the problem, we used to use `Path.append` which is smart when it comes to dropping device segments on Windows.
```java
public IPath append(String tail) {
    //optimize addition of a single segment
    if (tail.indexOf(SEPARATOR) == -1 && tail.indexOf("\\") == -1 && tail.indexOf(DEVICE_SEPARATOR) == -1) { //$NON-NLS-1$
        int tailLength = tail.length();
        if (tailLength < 3) {
            //some special cases
            if (tailLength == 0 || ".".equals(tail)) { //$NON-NLS-1$
                return this;
            }
            if ("..".equals(tail)) //$NON-NLS-1$
                return removeLastSegments(1);
        }
        //just add the segment
        int myLen = segments.length;
        String[] newSegments = new String[myLen + 1];
        System.arraycopy(segments, 0, newSegments, 0, myLen);
        newSegments[myLen] = tail;
        return new Path(device, newSegments, separators & ~HAS_TRAILING);
    }
    //go with easy implementation
    return append(new Path(tail));
}
```

After switching back to a commit (4e3c1e15edd4c8f34574b279bf2fc383651facd2) before the SADL web changes, the `file` URIs are supported like this for external models; if the model is under `C:\Users\username\Desktop\my-model.owl` and the URL is `file:/c:/Users/username/Desktop/my-model.owl` then the file will be downloaded to `YourProject/externalmodels/Users/username/Desktop/mu-model.owl` So the drive is dropped. Are we OK with this approach?

**Comment by crapo** [comment]
I think so. The alternative would be to look in the OWL file and extract the base URI and use that, which could also be done for http URLs, but I think this is probably better as the path coincides with what's in the .url file. Saving under URI's would make it harder to see what came from where.

**Comment by kittaakos** [comment]
Thanks for confirming, @crapo. I will drop the device segment (`C:\`, `D:\`, etc...) on Windows when calculating the download path. Eclipse `Path` does the same. The fix will be ready today.

**Comment by kittaakos** [comment]
I have fixed the path on both UNIX and Windows.

The external model definition was:
```
--This is a list of URLs of OWL model files to add to the external models directory for this project.
--TO DO:  Add your list of URLs
file:/c:/Users/kittaakos/Desktop/time-entry.owl
file:/C:/Users/kittaakos/Desktop/path%20with%20ws/time-entry.owl
http://sadl.sourceforge.net/owl/aulo.owl
http://sadl.sourceforge.net/owl/apvf.owl
```

screen shot 2018-11-20 at 17 16 22

On UNIX, the file URI can be either `file:///Users/blabla` or `file:/Users/blabla`.

**Comment by kittaakos** [comment]
The changes have been merged to `AWC-ServicesConfig` via  https://github.com/crapo/sadlos2/commit/402cd6207d19e33eb8eaf693be5ec74aa7653339.

**Pull request closed without merging**
