### PR TITLE
Allow omitting ‘with’ or ‘has’ (fixes #243)

### LINKED ISSUE #243: Sadl Grammar changes?
I've made some SADL grammar changes to extend functionality as requested by users. I'd like to review these with @svenefftinge.

Also there is a **significant** need for a grammar enhancement to allow the SADL 2 construct 
`<subject> <property> `
and not just 
`<subject> has <property>` in SubjHasProp expressions.

### PR DESCRIPTION
**Pull request by svenefftinge**

### CODE REVIEW

**Comment by kittaakos** [comment]
You have test failures. :(

**Comment by svenefftinge** [comment]
Oh wow, we have a CI! :)

**Comment by svenefftinge** [comment]
I had to do a backward incompatible change in that the comma-separated types are no longer allowed. See https://github.com/crapo/sadlos2/pull/246/commits/adea40dea23ca9e25c2c67488d073e8523bd82c5#diff-e08783fd80e4260d9f67767e8f0677de

**Comment by crapo** [comment]
this was manually merged in some time ago and is part of modified grammar on development branch

**Pull request closed without merging**
